### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by TheSecretPenguin** [TropicSapling/P-plus#10]
How do I install it?

**Comment by TropicSapling** [comment]
Run ./compile.sh in a bash terminal. Currently there's no compilation file for other operating systems, but on Windows 10 you can activate developer mode and install bash.

**Comment by TropicSapling** [comment]
I'm assuming things are working fine since you haven't replied, so closing this issue now.

**Comment by TropicSapling** [comment]
@TheSecretPenguin I've changed the installation now; now you should run `./install.sh` :)

(If you want to develop or debug, use `./build.sh` and `./debug.sh` respectively)
