### ISSUE TITLE
Make the --run flag default

### ISSUE THREAD

**Issue by mytopdog** [TropicSapling/P-plus#118]
let's admit, nobody compiles the code and never runs it.

Just make another flag like `--norun`/`-nr` if you _really_ don't want to run it as soon as compilation is finished.

**Comment by TropicSapling** [comment]
let's admit, you've changed your username too many times for no reason.

Just change back to your normal username if you *really* want to change your username again.

**Comment by mytopdog** [comment]
That actually makes no sense

What does my name have anything to do with this

**Comment by mytopdog** [comment]
Also not a new name, a new account.

**Comment by TropicSapling** [comment]
well you changed the name of your old account too :P

**Comment by mytopdog** [comment]
once :P Also nice you reopened it, you finally agree :)

**Comment by TropicSapling** [comment]
It means I'm considering it :P

**Comment by TropicSapling** [comment]
Alternatively, perhaps I could replace `--run` with 2 subcommands: `ppc build` and `ppc run`? This is apparently done in both Rust and Go, which makes it a well-known syntax.

**Comment by TropicSapling** [comment]
> what was I thinking?
this should not be default at all
_- mytopdog, 2019-10-21 20:46_
