### ISSUE TITLE
Accept file input without .ppl

### ISSUE THREAD

**Issue by mytopdog** [TropicSapling/P-plus#122]
`ppc --run file` vs `ppc --run file.ppl`

Obviously, files will still have to have .ppl at the end, but the main point is that maybe have it so you don't have to add the extension when writing the command.

**Comment by TropicSapling** [comment]
This would require the compiler to first attempt to open `file` in case it exists, and try with `file.ppl` as a second option.

**Comment by TropicSapling** [comment]
Implemented in https://github.com/TropicSapling/P-plus/commit/b2bd61b75608778cf4b2831360eaca2ee523cc82
